# Add Homebrew to path
eval "$(/opt/homebrew/bin/brew shellenv)"

# Source antigen
source /opt/homebrew/share/antigen/antigen.zsh

# Install zsh plugins
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen apply

# Source custom aliases
source ~/.dotfiles/zsh/aliases
# Source custom git aliases
source ~/.dotfiles/zsh/git-shorthands
# Source custom prompts
source ~/.dotfiles/zsh/prompt

# Fix ghostty display issues when sudo -s, see https://github.com/ghostty-org/ghostty/issues/3335#issuecomment-2563510084
export TERM=xterm-256color